environment: #confluent cloud environment id
# new cluster configuration
cluster: 
  cloud:  # GCP, AWS or Azure
  region:  # cloud region
  display_name:  # cluster name
  availability:  # SINGLE_ZONE or MULTI_ZONE - basic are SINGLE_ZONE only. 
  type:  # basic, standard or dedicated
  cku: # optional for dedicated cluster, default = 1
  serviceAccount:  # optional: create a cluster API_KEY for the SACC.
  